const productos = [ //lista de productos en un array
    {id: 1,
    nombre:'Colonos de catan',
    precio: 80000,
    categoria: 'juego de mesa',
    stock: true,
    etiqueta:['colonos', 'catan', 'estrategia', 'comercio',]},
    
    {id: 2,
    nombre:'Reino Dragon',
    precio: 42000,
    categoria: 'juego de mesa',
    stock: true,
    etiqueta:['reino', 'amigos', 'dragon', 'heroes']},
    
    {id: 3,
    nombre:'Atenea',
    precio: 46000,
    categoria: 'juego de mesa',
    stock: true,
    etiqueta:'atenea'},

    {id: 4,
    nombre:'Digalo con memes',
    precio: 35000,
    categoria: 'cartas',
    stock: true,
    etiqueta:['humor', 'cartas']},

    {id: 5,
    nombre:'Remando en dulce de leche',
    precio: 31000, categoria: 'cartas',
    stock: true,
    etiqueta:['humor', 'cartas']},

    {id: 6,
    nombre:'Call of Cthulhu',
    precio: 89000,
    categoria: 'cartas',
    stock: true,
    etiqueta:['asdasd']},

    {id: 7,
    nombre:'Osito',
    precio: 35000,
    categoria: 'muñecos', 
    stock: true, 
    etiqueta:['niños']},

    {id: 8,
    nombre:'Princesa',
    precio: 40000, 
    categoria: 'muñecos', 
    stock: true, 
    etiqueta:['niños']},
]